name: xpublish-intake
channels:
  - conda-forge
dependencies:
  - conda-forge::python >=3.8,<3.13
  - conda-forge::pip

  - pip:
    - git+https://github.com/xarray-contrib/xpublish.git@main#egg=xpublish
